name: "sklearn-onnx"
platform: "onnxruntime_onnx"
max_batch_size: 0


input [
    {
        name: "X"
        data_type: TYPE_FP64
        dims: [ -1, 4 ]
    }
]

output [
    {
        name: "label"
        data_type: TYPE_INT64
        dims: [ -1 ]
    }
]

instance_group [
    {
        count: 2
        kind: KIND_CPU
    }
]

dynamic_batching: { }
